baseURL: https://rhythm113.dev/
locale: en-us
title: Mahbub Anam
enableRobotsTXT: true
pygmentsUseClasses: true
theme: PaperMod

languages:
  en:
    label: "English"
    weight: 1
    taxonomies:
      category: categories
      tag: tags
      series: series

markup:
  goldmark:
    renderer:
      unsafe: true

menu:
  main:
  - name: Home
    url: /
    weight: 1
  - name: Blog
    url: posts/
    weight: 2
  - name: About
    url: about/
    weight: 3

minify:
 disableXML: true

outputs:
  home:
  - HTML
  - RSS
  - JSON

params:
  author: Mahbub Anam
  comments: true
  defaultTheme: auto
  env: production
  social: true
  customCSS:
    - css/extended/header.css

  homeInfoParams:
    Title: Hello 👋
    Content: I am an undergrad student passionate about secure systems and development. I am learning low-level and web security testing, and I am currently employed at my university's IT department. Want to know more about me? visit my [About](/about/) section. Anyways, thanks for a visit :')

  socialIcons: # optional
    - name: "Facebook"
      url: "https://facebook.com/Rhythm113"
    - name: "Github"
      url: "https://github.com/rhythm113"
    - name: "Linkedin"
      url: "https://www.linkedin.com/in/rhythm113/"
    - name: email
      url: "mailto:me@rhythm113.dev"
    - name: "Telegram"
      url: "https://t.me/Rhythm113"

ShowCodeCopyButtons: true
ShowPostNavLinks: true
ShowReadingTime: true
ShowShareButtons: true
ShowToc: true
